spring.application.name=BNK_deposit

spring.profiles.include=secret

spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//192.168.0.156:1521/testdb
spring.datasource.username=bnkdb
spring.datasource.password=1234

mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml